# version: '3'
# services:
#    web:
#        build: .
#        command: python manage.py runserver 0.0.0.0:8000
#        environment:
#            - SECRET_KEY=$SECRET_KEY
#        volumes:
#            - .:/code
#        ports:
#            - "8000:8000"



 version: '3'
 services:
     web:
         build: .
         command: python manage.py runserver 0.0.0.0:8000
         #environment:
         #    - SECRET_KEY=$SECRET_KEY
         env_file:
           - ./env
         volumes:
             - .:/code
         ports:
             - "8021:8000"
