# Generated by Django 3.0.7 on 2020-06-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MDA_name', models.CharField(max_length=45)),
                ('project_recipient_name', models.CharField(max_length=45)),
                ('project_name', models.TextField()),
                ('project_amount', models.FloatField()),
                ('project_date', models.DateTimeField()),
            ],
        ),
    ]
