# Generated by Django 3.0.7 on 2020-06-19 20:36

from django.db import migrations, models
import excel_parser.models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_parser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelSaverModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_report_file', models.FileField(null=True, upload_to=excel_parser.models.upload_file_handler)),
            ],
        ),
    ]
