# Generated by Django 3.0.7 on 2020-06-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_parser', '0003_auto_20200620_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='MDA_name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='budget',
            name='project_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='budget',
            name='project_recipient_name',
            field=models.CharField(max_length=45),
        ),
    ]
