# Generated by Django 3.0.7 on 2020-06-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_budget', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='governmentfunctions',
            old_name='allocation',
            new_name='expenses',
        ),
        migrations.RenameField(
            model_name='governmentfunctions',
            old_name='total_allocation',
            new_name='percentage',
        ),
        migrations.AddField(
            model_name='governmentfunctions',
            name='code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='governmentfunctions',
            name='month',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
