# Generated by Django 3.0.7 on 2020-06-26 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_budget', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='economicrevenue',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='economicrevenue',
            name='budget',
        ),
    ]
