# Generated by Django 3.0.7 on 2020-06-29 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_budget', '0002_auto_20200628_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='governmentfunctions',
            old_name='percentage',
            new_name='total_expenses',
        ),
        migrations.RemoveField(
            model_name='governmentfunctions',
            name='code',
        ),
    ]
