# Generated by Django 3.0.8 on 2020-07-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=2083)),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
