# Generated by Django 3.0.8 on 2020-07-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MDA_name', models.CharField(max_length=100)),
                ('project_recipient_name', models.CharField(max_length=120)),
                ('project_name', models.TextField()),
                ('project_amount', models.FloatField()),
            ],
        ),
    ]
