# Generated by Django 3.0.8 on 2020-07-17 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excelApi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LinkUpload',
        ),
    ]
