# Generated by Django 3.0.8 on 2020-07-17 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0006_auto_20200713_1517'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExcelUpload',
        ),
    ]
